name: posts
env: production
services:
  - name: web
    type: web
    command: gunicorn core.wsgi:application --workers 3 --bind 0.0.0.0:8000
    env:
      - name: RENDER_ENVIRONMENT
        value: production
